### ISSUE TITLE
ImportError: cannot import name XMLTreeBuilder

### ISSUE THREAD

**Issue by vitaLee** [SublimeCodeIntel/SublimeCodeIntel#176]
Each time i try to make SublimeCodeIntel working i fail miserably.
I managed to get it working just once (magic) and after sublime restart it was gone again.
Running OSX 10.6.8.
The snippet i pasted is from sublime console and though it might be a result of a miconfiguration on my side i decided to post it first and maybe later link to the output of build.sh.

``` python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./SublimeCodeIntel.py", line 843, in on_modified
  File "./SublimeCodeIntel.py", line 233, in guess_lang
  File "./SublimeCodeIntel.py", line 504, in codeintel_manager
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 142, in __init__
    self._register_modules(extra_module_dirs)
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 194, in _register_modules
    self._register_module(module_path)
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 215, in _register_module
    module = imp.load_module(module_name, *iinfo)
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/lang_html.py", line 50, in <module>
    from codeintel2.lang_xml import XMLLangIntel
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/lang_xml.py", line 54, in <module>
    import koXMLTreeService, koXMLDatasetInfo
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/koXMLDatasetInfo.py", line 55, in <module>
    from koCatalog import CatalogResolver
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/koCatalog.py", line 42, in <module>
    from koRNGElementTree import rng
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/koRNGElementTree.py", line 45, in <module>
    from elementtree import XMLTreeBuilder
ImportError: cannot import name XMLTreeBuilder
```

tried the development branch.
output of build.sh is 

``` bash
Mac OS X build!
Building PCRE (*nix)...
Building Sgmlop...
Patching Scintilla...
Building SilverCity...
Building cElementTree...
Done!
```

but still what i get inside sublime console is 

``` python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./SublimeCodeIntel.py", line 917, in run
  File "./SublimeCodeIntel.py", line 233, in guess_lang
  File "./SublimeCodeIntel.py", line 504, in codeintel_manager
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 142, in __init__
    self._register_modules(extra_module_dirs)
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 194, in _register_modules
    self._register_module(module_path)
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 215, in _register_module
    module = imp.load_module(module_name, *iinfo)
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/lang_html.py", line 50, in <module>
    from codeintel2.lang_xml import XMLLangIntel
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/codeintel2/lang_xml.py", line 54, in <module>
    import koXMLTreeService, koXMLDatasetInfo
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/koXMLDatasetInfo.py", line 55, in <module>
    from koCatalog import CatalogResolver
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/koCatalog.py", line 42, in <module>
    from koRNGElementTree import rng
  File "/Users/vitalee/Library/Application Support/Sublime Text 2/Packages/SublimeCodeIntel/libs/koRNGElementTree.py", line 45, in <module>
    from elementtree import XMLTreeBuilder
ImportError: cannot import name XMLTreeBuilder
```

**Comment by Rimevel** [comment]
Also having this issue now :/ Only packages installed are Haxe-sublime-bundle and this one.
