### ISSUE TITLE
CodeIntelError: style_at_pos binary search sentinel

### ISSUE THREAD

**Issue by Ahmad-Dukhan** [SublimeCodeIntel/SublimeCodeIntel#259]
Hi, 

My Code-Intel is not working any more when ever I try to go to definition I get this error 

`````` python
Traceback (most recent call last):
  File "./SublimeCodeIntel.py", line 698, in _codeintel
  File "~/.config/sublime-text-2/Packages/SublimeCodeIntel/libs/codeintel2/buffer.py", line 205, in preceding_trg_from_pos
    return self.langintel.preceding_trg_from_pos(self, pos, curr_pos)
  File "~/.config/sublime-text-2/Packages/SublimeCodeIntel/libs/codeintel2/langintel.py", line 423, in preceding_trg_from_pos
    start_style = accessor.style_at_pos(pos-1)
  File "~/.config/sublime-text-2/Packages/SublimeCodeIntel/libs/codeintel2/accessor.py", line 194, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "~/.config/sublime-text-2/Packages/SublimeCodeIntel/libs/codeintel2/accessor.py", line 190, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!
Done 'Python' CodeIntel! Full CodeIntel took ~2s```
``````

**Comment by cheoAlejo** [comment]
Hey @nikolov-tmw that was a nice hack, i was having the same problem and now is working. After 3 years, have you had any issue with the "55" number ? Could the problem be related to large files (many lines of code) ? Anyway, thanks for the hack.

**Comment by nikolov-tmw** [comment]
@cheoAlejo thanks, glad it's working for you too! Well, actually I had totally forgotten about this and since I had reinstalled my computer and Sublime Text with it for quite a few times already, I didn't have the hack in place any more. I just went in and added it back in place and it does seem to work a bit better(I was having a problem with autocomplete for native PHP functions). Still have no clue what difference it makes bumping up the `sentinel` variable  :smiley:
