### ISSUE TITLE
TypeError: must be str, not bytes in codeintel.log when trying to do anything

### ISSUE THREAD

**Issue by cclough2** [SublimeCodeIntel/SublimeCodeIntel#333]
I'm developing on a Python project, and any time I try to use any of SublimeCodeIntels features on python code, I get the following erorr message in codeintel.log

Doing CodeIntel for 'Python' (hold on)...
eval 'clear_all_session_values' at provider.py#82  <Trigger 'python-defn-defn' at 2949 (explicit)>
start scope is (<Element 'scope' at 0x108372668>, ['LoginServer', 'post'])
find 'clear_all_session_values ...' starting at (<Element 'scope' at 0x108372668>, ['LoginServer', 'post']):
Unexpected error with evaluator: 'clear_all_session_values' at provider.py#82
Traceback (most recent call last):
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree.py", line 331, in eval
    defns = self.eval_defns()
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_python.py", line 195, in eval_defns
    hit = self._hit_from_citdl(self.expr, start_scoperef, defn_only=True)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_python.py", line 418, in _hit_from_citdl
    hit, nconsumed = self._hit_from_first_part(tokens, scoperef)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_python.py", line 490, in _hit_from_first_part
    = self._hit_from_elem_imports(tokens, elem)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_python.py", line 690, in _hit_from_elem_imports
    hit, nconsumed = self.__hit_from_elem_imports(tokens, elem)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_python.py", line 552, in __hit_from_elem_imports
    orig_libs = self.libs
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_python.py", line 161, in libs
    self._libs = self.buf.libs
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_python.py", line 700, in libs
    return self.langintel.libs_from_buf(self)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_python.py", line 643, in libs_from_buf
    libs += self._buf_indep_libs_from_env(env)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_python.py", line 608, in _buf_indep_libs_from_env
    paths_from_libname["envlib"]))
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/database.py", line 944, in get_lang_lib
    return lang_zone.get_lib(name, dirs)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/langlib.py", line 1315, in get_lib
    langdirslib.ensure_all_dirs_scanned()
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/langlibbase.py", line 69, in ensure_all_dirs_scanned
    dir, ctlr=ctlr, reporter=lambda msg: None)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/langlibbase.py", line 104, in ensure_dir_scanned
    lang=self.lang)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 462, in buf_from_path
    follow_symlinks=True)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/textinfo.py", line 191, in textinfo_from_path
    quick_determine_lang=quick_determine_lang)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/textinfo.py", line 273, in init_from_path
    self._classify_encoding(lidb, suggested_encoding=encoding)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/textinfo.py", line 621, in _classify_encoding
    norm_emacs_encoding = _norm_encoding(emacs_encoding)
  File "/Users/cclough/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/textinfo.py", line 1493, in _norm_encoding
    return codecs.lookup(encoding).name
TypeError: must be str, not bytes
done eval: eval error
Done 'Python' CodeIntel! Full CodeIntel took 68ms

I'm in Sublime Text 3 on Mac OS X 10.7.5

**Comment by cgrossde** [comment]
+1, just ran into this. Switching to development branch still fixes the problem.
