### ISSUE TITLE
Codeintel fails with Perl in ST3

### ISSUE THREAD

**Issue by atonks** [SublimeCodeIntel/SublimeCodeIntel#344]
Codeintel does not seem to function correctly when processing a Perl file in ST3.  On alt clicking a variable, codeintel processes for 30 seconds or so, and then nothing happens.  The log file contains the following information:

```
Starting logging SublimeCodeIntel v2.0.6 rev GIT-unknown (1382607064) on Thu Oct 24 10:32:45 2013
=================================================================================================
+ Info: processing `Perl': please wait...
Updating indexes for 'Perl'... The first time this can take a while.
scan_purelang: path: 'C:\\Users\\user\\perl_script.pl' lang: Perl
unexpected error scanning `tld_stats_print_ids'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\citadel.py", line 265, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_perl.py", line 1407, in scan_purelang
    return perlcile.scan_purelang(buf)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\perlcile.py", line 120, in scan_purelang
    tree = parser.produce_CIX()
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 1496, in produce_CIX
    return self.get_CIX(actual_mtime)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 1491, in get_CIX
    self.printContents(self.moduleName, currNode)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 956, in printContents
    self.moduleInfo.printVariables(mainInfo, moduleNode)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 710, in printVariables
    variables.sort(sorter1)
TypeError: must use keyword argument for key function
Doing CodeIntel for 'Perl' (hold on)...
+ Info: Doing CodeIntel for 'Perl' (hold on)...
```

I'm using ST3 on Windows 7, with ActivePerl 5.14.2.  If I can provide any more details, let me know.

**Comment by andrewsawczyn** [comment]
You should check out issue #370 as some of these are known issues.  There is a fix available but you'll need to apply the patch or edit the code yourself for now.

https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/370

**Comment by Kronuz** [comment]
It's in master and development now. I'll be integrated in v2.1.2
