### ISSUE TITLE
codeintel fails with the "ImportError: /lib64/libc.so.6"

### ISSUE THREAD

**Issue by imkin** [SublimeCodeIntel/SublimeCodeIntel#352]
Hi I have centos 6 box and tried to install sublimecodeIntel[SCI] and found the following error.

[snip from the console]
Reloading plugin /home/superman/.config/sublime-text-2/Packages/SublimeCodeIntel/SublimeCodeIntel.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./SublimeCodeIntel.py", line 99, in <module>
    from codeintel2.common import CodeIntelError, EvalTimeout, LogEvalController, TRG_FORM_CPLN, TRG_FORM_CALLTIP, TRG_FORM_DEFN
  File "/home/superman/.config/sublime-text-2/Packages/SublimeCodeIntel/libs/codeintel2/common.py", line 86, in <module>
    import SilverCity
  File "/home/superman/.config/sublime-text-2/Packages/SublimeCodeIntel/libs/SilverCity/**init**.py", line 1, in <module>
    import _SilverCity
  File "/home/superman/.config/sublime-text-2/Packages/SublimeCodeIntel/libs/_SilverCity.py", line 42, in <module>
    from _linux_libcpp6_x86_64_py26._SilverCity import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/superman/.config/sublime-text-2/Packages/SublimeCodeIntel/arch/_linux_libcpp6_x86_64_py26/_SilverCity.so)

I am new to SCI and had to some digging to find what the issue was.

Centos 6 comes with glibc version 2.12 and silversity was compiled against 2.14. Centos will not get 2.14 for sometime now. Is there a workaround for this? What is the version of SCI that was built with 2.12.

Thanks.

**Comment by Mydrako** [comment]
Sorry to bump up a old thread but I am also using CentOS 6, and I am facing the same issue as imkin. Is there any version of codeIntel that we can use that is compatible?
