### ISSUE TITLE
"TypeError: must use keyword argument for key function", in perl_parser.py

### ISSUE THREAD

**Issue by asketak** [SublimeCodeIntel/SublimeCodeIntel#370]
When I use SublimeCodeIntel for the first time, it process file for long time and does not work. Here is my codeintel.log:

```

Starting logging SublimeCodeIntel v2.0.6 rev GIT-unknown (1388662102) on Thu Jan  2 12:39:49 2014
=================================================================================================
+ Info: processing `Perl': please wait...
Updating indexes for 'Perl'... The first time this can take a while.
scan_purelang: path: 'C:\\Users\\xxx\\Desktop\\eclipse-workspace\\Staging\\Staging\\ATPLoader.pm' lang: Perl
unexpected error scanning `ATPLoader.pm'
Traceback (most recent call last):
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\citadel.py", line 265, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\lang_perl.py", line 1407, in scan_purelang
    return perlcile.scan_purelang(buf)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perlcile.py", line 120, in scan_purelang
    tree = parser.produce_CIX()
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 1496, in produce_CIX
    return self.get_CIX(actual_mtime)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 1491, in get_CIX
    self.printContents(self.moduleName, currNode)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 956, in printContents
    self.moduleInfo.printVariables(mainInfo, moduleNode)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 710, in printVariables
    variables.sort(sorter1)
TypeError: must use keyword argument for key function
Doing CodeIntel for 'Perl' (hold on)...
eval '$self.prepareSourceData' at ATPLoader.pm#51  <Trigger 'perl-defn-defn' at 1126 (explicit)>
error evaluating '$self.prepareSourceData' at ATPLoader.pm#51: KeyError: 'Perl' (C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\tree_perl.py#326 in pre_eval)
error evaluating '$self.prepareSourceData' at ATPLoader.pm#51
Traceback (most recent call last):
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\manager.py", line 525, in run
    eval_sess.eval(self)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\tree.py", line 313, in eval
    self.pre_eval()
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\tree_perl.py", line 326, in pre_eval
    curr_blob = self.buf.blob_from_lang[self.trg.lang]
KeyError: 'Perl'
done eval: unexpected eval error
Done 'Perl' CodeIntel! Full CodeIntel took 157ms
+ Info: processing `Perl': please wait...
Updating indexes for 'Perl'... The first time this can take a while.
scan_purelang: path: 'C:\\Users\\xxx\\Desktop\\eclipse-workspace\\Staging\\Staging\\ATPLoader.pm' lang: Perl
unexpected error scanning `ATPLoader.pm'
Traceback (most recent call last):
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\citadel.py", line 265, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\lang_perl.py", line 1407, in scan_purelang
    return perlcile.scan_purelang(buf)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perlcile.py", line 120, in scan_purelang
    tree = parser.produce_CIX()
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 1496, in produce_CIX
    return self.get_CIX(actual_mtime)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 1491, in get_CIX
    self.printContents(self.moduleName, currNode)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 956, in printContents
    self.moduleInfo.printVariables(mainInfo, moduleNode)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\perl_parser.py", line 710, in printVariables
    variables.sort(sorter1)
TypeError: must use keyword argument for key function
Doing CodeIntel for 'Perl' (hold on)...
eval '$self.prepareSourceData' at ATPLoader.pm#51  <Trigger 'perl-defn-defn' at 1126 (explicit)>
error evaluating '$self.prepareSourceData' at ATPLoader.pm#51: KeyError: 'Perl' (C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\tree_perl.py#326 in pre_eval)
error evaluating '$self.prepareSourceData' at ATPLoader.pm#51
Traceback (most recent call last):
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\manager.py", line 525, in run
    eval_sess.eval(self)
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\tree.py", line 313, in eval
    self.pre_eval()
  File "C:\sublime\Data\Packages\SublimeCodeIntel\libs\codeintel2\tree_perl.py", line 326, in pre_eval
    curr_blob = self.buf.blob_from_lang[self.trg.lang]
KeyError: 'Perl'
done eval: unexpected eval error
Done 'Perl' CodeIntel! Full CodeIntel took 129ms

```

**Comment by andrewsawczyn** [comment]
This is still broken in the latest release.  Will fixing this for ST3 break ST2?

**Comment by ewildgoose** [comment]
I *think* most of the rest of the code is already adapted this way - the above seems like an oversight on one part of the code. 

So I don't think fixing things will make it *worse* for ST2.

**Comment by Kronuz** [comment]
It's in master and development now. I'll be integrated in v2.1.2
