### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8932: ordinal not in range(128)

### ISSUE THREAD

**Issue by asoki** [SublimeCodeIntel/SublimeCodeIntel#454]
SublimeCodeintel v2.1.1 (2015-01-14):
Sublime 2.0.2 Build 2221
OS X 10.6.8
codeintel not working after the update

Traceback (most recent call last):
  File "./sublime_plugin.py", line 205, in on_activated
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 204, in <lambda>
  File "./SublimeCodeIntel.py", line 1442, in on_activated
  File "./SublimeCodeIntel.py", line 1373, in update
  File "./SublimeCodeIntel.py", line 1353, in needsUpdate
  File "./SublimeCodeIntel.py", line 1279, in project_file_name
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8932: ordinal not in range(128)

**Comment by inovek** [comment]
Same problem, same issue, fired when CMD+Z hotkey pushed. (Undo don't work because of this)

**Comment by misern2** [comment]
Same problem with same OS (10.9.5)  and same version Build (2.0.2) Build 2221

**Comment by Kronuz** [comment]
This was resolved by #456. I'll make a release later today with this and a couple other fixes.
