### ISSUE TITLE
Autocomplete Fail ST3 Ruby

### ISSUE THREAD

**Issue by kaelumania** [SublimeCodeIntel/SublimeCodeIntel#455]
When i try to run autocomplete, i get no suggestions, but the following log:

```
Starting logging SublimeCodeIntel v2.1.1 rev GIT-unknown (1421317821) on Thu Jan 15 11:37:08 2015
=================================================================================================
Updating indexes for 'Ruby'... The first time this can take a while.
Doing CodeIntel for 'Ruby' (hold on)...
eval 'Array' at user.rb#39  <Trigger 'ruby-complete-literal-methods' at 1301 (explicit)>
Unexpected error with evaluator: 'Array' at user.rb#39
Traceback (most recent call last):
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree.py", line 317, in eval
    cplns = self.eval_cplns()
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_ruby.py", line 220, in eval_cplns
    self._base_scoperefs = self._calc_base_scoperefs(start_scoperef)
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_ruby.py", line 328, in _calc_base_scoperefs
    scoperefs = [curr_scoperef, (self.built_in_blob, [])]
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_ruby.py", line 1040, in built_in_blob
    if isinstance(self.libs[-1], StdLib):
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/tree_ruby.py", line 164, in libs
    self._libs = self.langintel.libs_from_buf(self.buf)
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_ruby.py", line 337, in libs_from_buf
    libs = self._buf_indep_libs_from_env(env)[:]
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_ruby.py", line 486, in _buf_indep_libs_from_env
    extra_dirs = self._extra_dirs_from_env(env)
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 96, in _extra_dirs_from_env
    self._expand_extra_dirs(env, extra_dirs)
  File "/Users/stephanepping/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 84, in _expand_extra_dirs
    return util.gen_dirs_under_dirs(extra_dirs, max_depth=max_depth)
NameError: global name 'util' is not defined
done eval: eval error
Done 'Ruby' CodeIntel! Full CodeIntel took 323ms
```

**Comment by wizza-smile** [comment]
it's working in SublimeCodeIntel3!

Find it here:
https://github.com/wizza-smile/SublimeCodeIntel3

**Comment by Kronuz** [comment]
I'll make a release later today with this and a couple other fixes.
