### ISSUE TITLE
Install SublimeCodeIntel failed

### ISSUE THREAD

**Issue by legend0702** [SublimeCodeIntel/SublimeCodeIntel#473]
My cp is win7 32-bit and sublime' version is 3065 
I download a .zip from "http://sublimecodeintel.github.io/SublimeCodeIntel/".
And decompressed to my "~\AppData\Roaming\Sublime Text 3\Packages" named "SublimeCodeIntel".
Then open the sublime and the SublimeCodeIntel isn't work..?

The  console(ctrl+`):
reloading plugin SublimeCodeIntel.SublimeCodeIntel
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3 3065\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\HongQing.Zhu\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 109, in <module>
    from codeintel2.common import CodeIntelError, EvalTimeout, LogEvalController, TRG_FORM_CPLN, TRG_FORM_CALLTIP, TRG_FORM_DEFN
  File "C:\Users\HongQing.Zhu\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\common.py", line 86, in <module>
    import SilverCity
  File "C:\Users\HongQing.Zhu\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\SilverCity\__init__.py", line 19, in <module>
    import LanguageInfo
ImportError: No module named 'LanguageInfo'

Why?How can i do?

**Comment by Kronuz** [comment]
You probably downloaded the version for Sublime Text 2. It's easier and better to install using Package Control, see the instructions about it in the *Install* section of the README (https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/master/README.rst) or download the `development` branch zip file (https://github.com/SublimeCodeIntel/SublimeCodeIntel/archive/development.zip).

**Comment by legend0702** [comment]
@Kronuz 
Yes,you probably right! Thx :)

**Comment by evandrocoan** [comment]
@Kronuz, thanks. This worked for me. But the stranger is the package manager installed the wrong version.
