### ISSUE TITLE
Package load fails on Windows 8

### ISSUE THREAD

**Issue by ancarius** [SublimeCodeIntel/SublimeCodeIntel#487]
After cloning the repo into my Sublime Text packages directory I get the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\NullDivision\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 109, in <module>
    from codeintel2.common import CodeIntelError, EvalTimeout, LogEvalController, TRG_FORM_CPLN, TRG_FORM_CALLTIP, TRG_FORM_DEFN
  File "C:\Users\NullDivision\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\common.py", line 86, in <module>
    import SilverCity
  File "C:\Users\NullDivision\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\SilverCity\__init__.py", line 19, in <module>
    import LanguageInfo
ImportError: No module named 'LanguageInfo'
```

From what I can see there's something fishy in the LanguageInfo class file. A lot of the methods are outside the class for starters, some of the methods are defined but never used (that's just a guess, they might have some concatenated/dynamic method call).

**Comment by lennartcl** [comment]
Duplicate of https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/473? See the advice there.
