### ISSUE TITLE
Right mouse buttom + "Jump to simbol definition" does not work

### ISSUE THREAD

**Issue by KES777** [SublimeCodeIntel/SublimeCodeIntel#489]
how to reproduce:
1. move cursor to anywhere from function name you want to jump.
2. right click on function name you want to jump
3. select from menu "Jump to simbol definition"
You will be jumped to that definition the curson is on. instead of that you have right clicked.

**Comment by dominic-ew** [comment]
Same problem here with javascript (works ok with PHP)

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "/Users/dominicrose/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1820, in is_enabled
    return super(SublimecodeintelEnableLiveCommand, self).is_enabled(False, False)
  File "/Users/dominicrose/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "/Users/dominicrose/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "/Users/dominicrose/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1830, in is_enabled
    return super(SublimecodeintelEnableLiveLangCommand, self).is_enabled(False, True)
  File "/Users/dominicrose/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "/Users/dominicrose/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

**Comment by wizza-smile** [comment]
You might consider switching to CodeComplice. It is a fork of SublimeCodeIntel that has this and other bugs fixed. Find it at packagecontrol.io!

**Comment by KES777** [comment]
ok, I will try.
thank you
