### ISSUE TITLE
Constant reindex in Ruby

### ISSUE THREAD

**Issue by erikLovesMetal** [SublimeCodeIntel/SublimeCodeIntel#505]
When working in Ruby.  It reindexes on basically every autocomplete.   Thus freezing ST until it finishes each time.  I have deleted the ~/.codeintel  and reindexed multiple times.  Using ST3 build 3083.  With latest version of SublimeCodeIntel as of today.  Working perfectly in JS, SASS, etc.   I only have this issue in Ruby.

Thanks 
erik

**Comment by Kronuz** [comment]
This is really weird... do the logs say anything? Would you be willing to try the beta version of SublimeCodeIntel 3?

**Comment by erikLovesMetal** [comment]
@Kronuz the logs have a lots errors in them.

"TypeError: unorderable types: NoneType() < str()
unexpected error scanning `order.rb'"

"TypeError: unorderable types: NoneType() < str()
unexpected error scanning `search.rb'"

"TypeError: unorderable types: str() < NoneType()
unexpected error scanning `alert.rb'"

This basically continues for a whole bunch of files.  If i were to try the ST3 beta would i have to resetup everything (configs, packages, etc)?

Thanks
erik

**Comment by nekromoff** [comment]
constant errors:
Traceback (most recent call last):
  File "/home/xxx/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 346, in _set_status
    lineno = view.rowcol(view_sel[0].end())[0] if view_sel else 0
  File "/opt/sublime_text/sublime.py", line 513, in __getitem__
    raise IndexError()
