### ISSUE TITLE
Sublime text + Ruby = CPU goes to 100%, constant reindexing.

### ISSUE THREAD

**Issue by lifeBalance** [SublimeCodeIntel/SublimeCodeIntel#523]
It hasn't happened with another languages. With ruby though, SublimeCodeIntel it's unusable.
I tried deleting the ``~/.codeintel`` folder, but didn't help.
```
Starting logging SublimeCodeIntel v2.2.0 rev GIT-unknown (1427451508) on Mon Jun  8 12:17:27 2015
=================================================================================================
Updating indexes for 'Ruby'... The first time this can take a while.
Doing CodeIntel for 'Ruby' (hold on)...
Done 'Ruby' CodeIntel! Full CodeIntel took 545ms
Doing CodeIntel for 'Ruby' (hold on)...
Done 'Ruby' CodeIntel! Full CodeIntel took 1ms
Doing CodeIntel for 'Ruby' (hold on)...
eval 'APP' at init.rb#1  <Trigger 'ruby-complete-names' at 0>
+ Info: Doing CodeIntel for 'Ruby' (hold on)...
+ Info: Updating indexes... The first time this can take a while. Do not despair!
unexpected error scanning `session.rb'
Traceback (most recent call last):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 226, in blob_from_lang
    self._load_buf_data_once()
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 166, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/database.py", line 1067, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/langlib.py", line 831, in get_buf_data
    % (buf.lang, buf.path))
codeintel2.common.NotFoundInDatabase: Ruby buffer '/Users/don/.rbenv/versions/2.2.2/lib/ruby/2.2.0/cgi/session.rb' not found in database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 292, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_ruby.py", line 1636, in scan_purelang
    tree = rubycile.scan_purelang(buf.accessor.text, buf.path)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/rubycile.py", line 287, in scan_purelang
    "Ruby", "Ruby")
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 227, in produce_elementTree_cix
    produce_elementTree_contents_cix(parse_tree, module_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 237, in produce_elementTree_contents_cix
    visit_children_get_cix(parse_tree, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 189, in class_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, classref_etree_cix)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 178, in common_module_class_cix
    visit_children_get_cix(parse_tree_node, class_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 189, in class_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, classref_etree_cix)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 175, in common_module_class_cix
    get_vars_cix(parse_tree_node, class_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 162, in get_vars_cix
    "__instancevar__ __local__")
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 143, in _get_vars_helper
    kind_name, {})):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 78, in sort_by_lines
    intermed.sort()
TypeError: unorderable types: NoneType() < str()
unexpected error scanning `scanf.rb'
Traceback (most recent call last):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 226, in blob_from_lang
    self._load_buf_data_once()
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 166, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/database.py", line 1067, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/langlib.py", line 831, in get_buf_data
    % (buf.lang, buf.path))
codeintel2.common.NotFoundInDatabase: Ruby buffer '/Users/don/.rbenv/versions/2.2.2/lib/ruby/2.2.0/scanf.rb' not found in database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 292, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_ruby.py", line 1636, in scan_purelang
    tree = rubycile.scan_purelang(buf.accessor.text, buf.path)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/rubycile.py", line 287, in scan_purelang
    "Ruby", "Ruby")
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 227, in produce_elementTree_cix
    produce_elementTree_contents_cix(parse_tree, module_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 237, in produce_elementTree_contents_cix
    visit_children_get_cix(parse_tree, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 206, in module_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, ilk='namespace')
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 178, in common_module_class_cix
    visit_children_get_cix(parse_tree_node, class_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 189, in class_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, classref_etree_cix)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 175, in common_module_class_cix
    get_vars_cix(parse_tree_node, class_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 162, in get_vars_cix
    "__instancevar__ __local__")
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 143, in _get_vars_helper
    kind_name, {})):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 78, in sort_by_lines
    intermed.sort()
TypeError: unorderable types: NoneType() < str()
unexpected error scanning `shell.rb'
Traceback (most recent call last):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 226, in blob_from_lang
    self._load_buf_data_once()
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 166, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/database.py", line 1067, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/database/langlib.py", line 831, in get_buf_data
    % (buf.lang, buf.path))
codeintel2.common.NotFoundInDatabase: Ruby buffer '/Users/don/.rbenv/versions/2.2.2/lib/ruby/2.2.0/shell.rb' not found in database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 292, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_ruby.py", line 1636, in scan_purelang
    tree = rubycile.scan_purelang(buf.accessor.text, buf.path)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/rubycile.py", line 287, in scan_purelang
    "Ruby", "Ruby")
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 227, in produce_elementTree_cix
    produce_elementTree_contents_cix(parse_tree, module_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 237, in produce_elementTree_contents_cix
    visit_children_get_cix(parse_tree, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 189, in class_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, classref_etree_cix)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 178, in common_module_class_cix
    visit_children_get_cix(parse_tree_node, class_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 189, in class_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, classref_etree_cix)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 175, in common_module_class_cix
    get_vars_cix(parse_tree_node, class_cix_node)
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 162, in get_vars_cix
    "__instancevar__ __local__")
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 143, in _get_vars_helper
    kind_name, {})):
  File "/Users/don/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/parser_cix.py", line 78, in sort_by_lines
    intermed.sort()
TypeError: unorderable types: NoneType() < str()
done eval: timed out
Just finished indexing 'Ruby'! Please try again. Full CodeIntel took ~20s
+ Info: Just finished indexing 'Ruby'! Please try again. Full CodeIntel took ~20s
Updating indexes for 'Ruby'... The first time this can take a while.
Doing CodeIntel for 'Ruby' (hold on)...
Done 'Ruby' CodeIntel! Full CodeIntel took 219ms
Doing CodeIntel for 'Ruby' (hold on)...
+ Info: processing `Ruby': please wait...
+ Info: Updating indexes... The first time this can take a while. Do not despair!
done eval: timed out
Just finished indexing 'Ruby'! Please try again. Full CodeIntel took ~20s
+ Info: Just finished indexing 'Ruby'! Please try again. Full CodeIntel took ~20s
Updating indexes for 'Ruby'... The first time this can take a while.
Doing CodeIntel for 'Ruby' (hold on)...
+ Info: Doing CodeIntel for 'Ruby' (hold on)...
done eval: timed out
Just finished indexing 'Ruby'! Please try again. Full CodeIntel took ~20s
+ Info: Just finished indexing 'Ruby'! Please try again. Full CodeIntel took ~20s
+ Info: processing `JSON': please wait...
```

**Comment by Kronuz** [comment]
I think we all should be moving to the newest SublimeCodeIntel (the one in beta, in the oop branch) which is much more stable and faster. The thing is it requires the host machine to have Python 2 installed and also the CodeIntel Python package (https://pypi.python.org/pypi/CodeIntel)

**Comment by Kronuz** [comment]
Installing newest SublimeCodeIntel:
http://kronuz.io/using-sublimecodeintel-v30.html

**Comment by Roguedeus** [comment]
Is there a reason why this would clash with VS2010?

```
    running build_ext

    building 'codeintel.SilverCity._SilverCity' extension

    creating build\temp.win32-3.4

    creating build\temp.win32-3.4\Release

    creating build\temp.win32-3.4\Release\silvercity

    creating build\temp.win32-3.4\Release\silvercity\PySilverCity

    creating build\temp.win32-3.4\Release\silvercity\PySilverCity\Src

    creating build\temp.win32-3.4\Release\silvercity\Lib

    creating build\temp.win32-3.4\Release\silvercity\Lib\Src

    creating build\temp.win32-3.4\Release\scintilla

    creating build\temp.win32-3.4\Release\scintilla\src

    creating build\temp.win32-3.4\Release\scintilla\lexlib

    creating build\temp.win32-3.4\Release\scintilla\lexers

    creating build\temp.win32-3.4\Release\pcre

    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo
 /Ox /MD /W3 /GS- /DNDEBUG -DPCRE_STATIC -DHAVE_STRERROR -DHAVE_MEMMOVE -DHAVE_B
COPY -DNEWLINE='\n' -DLINK_SIZE=2 -DMATCH_LIMIT=10000000 -DPOSIX_MALLOC_THRESHOL
D=10 -DEXPORT= -Iscintilla/src -Iscintilla/lexlib -Iscintilla/lexers -Iscintilla
/include -Isilvercity/PySilverCity/Src -Isilvercity/Lib/Src -Ipcre -IC:\Python34
\include -IC:\Python34\include /Tpsilvercity/PySilverCity/Src\PyLexerModule.cxx
/Fobuild\temp.win32-3.4\Release\silvercity/PySilverCity/Src\PyLexerModule.obj

    PyLexerModule.cxx

    c:\python34\include\pyconfig.h(64) : warning C4005: 'HAVE_STRERROR' : macro
redefinition

            command-line arguments :  see previous definition of 'HAVE_STRERROR'


    silvercity/PySilverCity/Src\PyLexerModule.cxx(332) : error C3861: 'PyString_
Check': identifier not found

    silvercity/PySilverCity/Src\PyLexerModule.cxx(338) : error C3861: 'PyString_
AsString': identifier not found

    silvercity/PySilverCity/Src\PyLexerModule.cxx(455) : error C3861: 'PyString_
FromString': identifier not found

    silvercity/PySilverCity/Src\PyLexerModule.cxx(479) : error C3861: 'Py_FindMe
thod': identifier not found

    silvercity/PySilverCity/Src\PyLexerModule.cxx(491) : error C2039: 'ob_type'
: is not a member of 'PyLexState'

            c:\users\rogue\appdata\local\temp\pip-build-p7ijy5i0\codeintel\silve
rcity\pysilvercity\src\PyLexerModule.h(27) : see declaration of 'PyLexState'

    silvercity/PySilverCity/Src\PyLexerModule.cxx(491) : error C2227: left of '-
>tp_name' must point to class/struct/union/generic type

    silvercity/PySilverCity/Src\PyLexerModule.cxx(490) : error C3861: 'PyString_
FromFormat': identifier not found

    silvercity/PySilverCity/Src\PyLexerModule.cxx(494) : error C2039: 'ob_type'
: is not a member of 'PyLexState'

            c:\users\rogue\appdata\local\temp\pip-build-p7ijy5i0\codeintel\silve
rcity\pysilvercity\src\PyLexerModule.h(27) : see declaration of 'PyLexState'

    silvercity/PySilverCity/Src\PyLexerModule.cxx(494) : error C2227: left of '-
>tp_name' must point to class/struct/union/generic type

    silvercity/PySilverCity/Src\PyLexerModule.cxx(493) : error C3861: 'PyString_
FromFormat': identifier not found

    silvercity/PySilverCity/Src\PyLexerModule.cxx(514) : error C2440: 'initializ
ing' : cannot convert from 'const char [12]' to 'Py_ssize_t'

            There is no context in which this conversion is possible

    silvercity/PySilverCity/Src\PyLexerModule.cxx(517) : error C2440: 'initializ
ing' : cannot convert from 'destructor' to 'printfunc'

            This conversion requires a reinterpret_cast, a C-style cast or funct
ion-style cast

    silvercity/PySilverCity/Src\PyLexerModule.cxx(519) : error C2440: 'initializ
ing' : cannot convert from 'getattrfunc' to 'setattrfunc'

            This conversion requires a reinterpret_cast, a C-style cast or funct
ion-style cast

    silvercity/PySilverCity/Src\PyLexerModule.cxx(522) : error C2440: 'initializ
ing' : cannot convert from 'reprfunc' to 'PyNumberMethods *'

            There is no context in which this conversion is possible

    silvercity/PySilverCity/Src\PyLexerModule.cxx(535) : error C2039: 'ob_type'
: is not a member of '_typeobject'

            c:\python34\include\object.h(334) : see declaration of '_typeobject'


    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\B
IN\\cl.exe' failed with exit status 2

    ----------------------------------------
    Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:
\\Users\\Rogue\\AppData\\Local\\Temp\\pip-build-p7ijy5i0\\codeintel\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record C:\Users\Rogue\AppData\Local\Temp\pip-x
ix6stxg-record\install-record.txt --single-version-externally-managed --compile"
 failed with error code 1 in C:\Users\Rogue\AppData\Local\Temp\pip-build-p7ijy5i
0\codeintel
```

**Comment by davidhq** [comment]
I have installed python package:
```
Installing collected packages: codeintel
  Running setup.py install for codeintel
Successfully installed codeintel-0.1.7
```

Then tried to run "Upgrade Package" in Sublime, but I get `There are no packages ready for upgrade`

![screen shot 2015-09-06 at 15 58 35](https://cloud.githubusercontent.com/assets/3899/9705250/288a2078-54bf-11e5-8c78-a8bd5e3b1d03.png)
