### ISSUE TITLE
Constant error in JavaScript

### ISSUE THREAD

**Issue by nemoDreamer** [SublimeCodeIntel/SublimeCodeIntel#525]
```log
+ Info: processing `JavaScript': please wait...
Exception in thread scanning thread:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/Users/philip/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 802, in _codeintel_scan
    mgr = codeintel_manager()
  File "/Users/philip/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 753, in codeintel_manager
    codeintel_database_dir = os.path.expanduser(settings_manager.get("codeintel_database_dir"))
  File "./posixpath.py", line 252, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'

Exception in thread scanning thread:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/Users/philip/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 802, in _codeintel_scan
    mgr = codeintel_manager()
  File "/Users/philip/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 753, in codeintel_manager
    codeintel_database_dir = os.path.expanduser(settings_manager.get("codeintel_database_dir"))
  File "./posixpath.py", line 252, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by JesusIslam** [comment]
Same here, using ST3 on Ubuntu 15.04

```
+ Info: processing `JavaScript': please wait...
Exception in thread scanning thread:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/home/dida/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 802, in _codeintel_scan
    mgr = codeintel_manager()
  File "/home/dida/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 753, in codeintel_manager
    codeintel_database_dir = os.path.expanduser(settings_manager.get("codeintel_database_dir"))
  File "./posixpath.py", line 252, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by nemoDreamer** [comment]
My SublimeCodeIntel is currently sadly disabled, as it no longer can find function definitions, expansion, etc... :panda_face:

**Comment by Kronuz** [comment]
I think we all should be moving to the newest SublimeCodeIntel (the one in beta, in the oop branch) which is much more stable and faster. The thing is it requires the host machine to have Python 2 installed and also the CodeIntel Python package (https://pypi.python.org/pypi/CodeIntel)

Installing newest (v3,0, aka oop) SublimeCodeIntel:
http://kronuz.io/using-sublimecodeintel-v30.html

Please try and see how it goes and if it fixes this issue. Report back if it works or not please.

**Comment by nemoDreamer** [comment]
Thanks! CodeIntel installation was a breeze (although I already had pip installed which if I remember correctly wasn't a breeze on my Mac). I'm no longer getting fatal errors, and the functionality seems to be trying its best from the logs.

But:
- "Preferences > Package Settings > SublimeCodeIntel" has disappeared.
- "Jump to Definition" fails to resolve. Is this because my project needs to be structured in a certain way, w/ explicit dependency definitions in each file?

I'm in a legacy project that uses global variables. `var SG` is defined in another file, a module `SG.util.ChainHelper` will be defined in another, and my current file uses `SG.util.ChainHelper.get_chain()`. SublimeCodeIntel can't find where that is defined, even though I'm loading the entire project. Apart from this not being modern code, what should I be doing differently?

Also:
Is there a way to exclude folders from intel? I can't find any relevant info in the README's or examples.

**Comment by JesusIslam** [comment]
The upgrade install just fine, but still doesn't seems to work for me. Code completion doesn't work as well as jump to definition. Ctrl shift space do nothing.

Also, the configuration menu disappeared.

**Comment by Kronuz** [comment]
Yes, configuration menu is gone; the configuration file is also currently gone too. I wanted to simplify things in this area (since a full rewrite was done) and so I wanted to see what is the bare minimum to have in such configurations and settings.

First thing that changed is now SublimeCodeIntel only looks and finds modules/files inside directories that you add to your Sublime Text project; so you *must* add all directories which contain your files to the project (Project -> Add Folder to Project). Directories that are part of the standard library of the language or generally in the path of the language aren't needed there, see bellow).

Languages and their paths and default include directories are currently still defined inside the SublimeCodeIntel.py file, *we need to figure out what needs to be put in a settings file and what not*, I just don't want to bloat the settings file again for no reason (it always was a source of confusion for many).

Once you add the directories containing your files to your project, you should be good to go and everything should start working; unless you have your language executables in non-standard paths, then you'll need to modify the dictionary in the SublimeCodeIntel.py file (for now).

**Comment by nemoDreamer** [comment]
I appreciate avoiding config file bloat! :+1: 

My Sublime Text project loads the root folder of my project, so all files should be accessible (and were indexed, by what I was seeing in the status bar), hence my surprise that it still can't resolve the definitions. Standard JS setup, no external paths, etc...

**Comment by tbaker4802** [comment]
I get the same error.  The update installed but it causes nothing to work, so i Downgrade and am gonna deal with the console errors.  

One thing is this related to portable installs? It doesn't happen on my laptop which has a installed sublime text.

both are build 3083.

Thanks,

**Comment by dacjames** [comment]
For me, this error went away when I created a user config (Preferences > Package Settings > SublimeCodeIntel > User Settings) that was an empty object: `{}`. Before the file was  either missing or empty (I don't remember which).

**Comment by objarni** [comment]
I get similar error to this in latest sublime text 3 (build 3114), just installed SublimeCodeIntel.

However, restarting ST was enough to get rid of it. Maybe a comment in the welcome-message explaining you need a restart for full fidelity CodeIntel...?

Here is the stack trace, which was repeated hundreds of times, in case you want to dig into it further:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 231, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 275, in <lambda>
    run_callback('on_pre_save', callback, lambda: callback.on_pre_save(v))
  File "[censored]\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1419, in on_pre_save
    lang = guess_lang(view)
  File "[censored]\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 459, in guess_lang
    mgr = None if settings_manager._settings_id is None else codeintel_manager()
  File "[censored]\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 753, in codeintel_manager
    codeintel_database_dir = os.path.expanduser(settings_manager.get("codeintel_database_dir"))
  File "./python3.3/ntpath.py", line 311, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by kingzez** [comment]
same issue in version build 3143, 
```
+ Info: processing `JavaScript': please wait...
WARNING:process:Could not import subprocess32 module, falling back to subprocess module
Exception in thread scanning thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/w/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 841, in _codeintel_scan
    buf = mgr.buf_from_content(content, lang, env, path or "<Unsaved>", 'utf-8')
  File "/Users/w/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 440, in buf_from_content
    buf = buf_class(self, accessor, env, path, encoding)
  File "/Users/w/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 146, in __init__
    Buffer.__init__(self, *args, **kwargs)
  File "/Users/w/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/buffer.py", line 123, in __init__
    (s, True) for s in self.comment_styles() + self.string_styles())
  File "/Users/w/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/buffer.py", line 643, in comment_styles
    state_map = styles.StateMap[self.lang]
AttributeError: 'module' object has no attribute 'StateMap'
```
and `./codeintel`
SublimeCodeintel 2.0.24
codeintel.log 's content 
```
Starting logging SublimeCodeIntel v2.2.0 rev GIT-unknown (1505563313) on Sat Sep 16 21:37:33 2017
=================================================================================================
+ Info: processing `JavaScript': please wait...
```
db folder is empty

**Comment by kenberkeley** [comment]
same in Build 3176

```
Exception in thread scanning thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\kennhuang\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 802, in _codeintel_scan
    mgr = codeintel_manager()
  File "C:\Users\kennhuang\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 753, in codeintel_manager
    codeintel_database_dir = os.path.expanduser(settings_manager.get("codeintel_database_dir"))
  File "./python3.3/ntpath.py", line 311, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'
```
