### ISSUE TITLE
Running Codeintel 3

### ISSUE THREAD

**Issue by xarnze** [SublimeCodeIntel/SublimeCodeIntel#528]
On win 8 I get:

Exception in thread Codeintel Manager 625227269512:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "C:\Users\aaron.polley\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\codeintel.py", line 611, in run
    self.init_child()
  File "C:\Users\aaron.polley\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\codeintel.py", line 336, in init_child
    import process
  File "C:\Users\aaron.polley\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\process.py", line 90, in <module>
    import winprocess
ImportError: No module named 'winprocess'

**Comment by nabijaczleweli** [comment]
Confirmed on WindowsXP x86

**Comment by PixelT** [comment]
Windows 10
+1
