### ISSUE TITLE
Getting CodeIntel: ERROR: Startup failed: Error initing child: [Errno 2] No such file or directory: 'codeintel'

### ISSUE THREAD

**Issue by rahmatawaludin** [SublimeCodeIntel/SublimeCodeIntel#561]
I'm using v3.0.0-beta6.
And theres no .codeintel folder created in `~`.
I've restarted Sublime Text 3.

What should I do? Thanks.. :)

**Comment by JohnPolansky** [comment]
I'm no expert, but I ran into this error.. and I "think" you need to install codeintel via pip.

pip install -U codeintel

I found a page discussing it here: http://kronuz.io/using-sublimecodeintel-v30.html

After I installed that I restarted sublime and you could see it "re-indexing" and my ~/.codeintel directory was created. 

Hope this helps

**Comment by rahmatawaludin** [comment]
@JohnPolansky hi, thanks for your help. So, first I install codeintel using `pip install -U codeintel` it yield error cannot write to some directory. Then I try again using `sudo pip install -U codeintel`, it return exception like this:
```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-kYfhru-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

Storing debug log for failure in /Users/rahmatawaludin/Library/Logs/pip.log
```

The pip.log looks like this https://gist.github.com/rahmatawaludin/6e3f9d2443121386e6ad

Then I try to run `codeintel`, it yield error like this:
```
Traceback (most recent call last):
  File "/usr/local/bin/codeintel", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: subprocess32
```

I'm no expert in python. Care to tell me what should I do next?

**Comment by JohnPolansky** [comment]
Unfortunately no I'm no expert on python either. when I ran "pip install -U codeintel" it ran perfectly I never had to use sudo. I'm using "homebrew" for my installation so my python was installed that way I did recently do an "brew update/upgrade" to upgrade everything perhaps I have slightly newer package that works better? As i understand it homebrew doesn't require sudo once installed, which I think is good because OSX now has that "questionable" SIP file protection which blocks modifying system files.. perhaps this is somehow what you are hitting?

 which python
/usr/local/bin/python

Sorry I couldn't be of more help. I never got my javascript working right using the 3.0.0 version I ended up switching back to the old 2.X version.. I still don't have automcompletion for node.js Like when I type "process." or "console." but if I type "express." that works.. it's very confusing.

Hope this helps.

**Comment by JohnPolansky** [comment]
I should have also mentioned I found confirmation you must install "codeintel" via PIP here:

https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/development/messages/3.0.0.txt

One thing is they did not specify the -U flag.. I did on mine.. according to the documentation the "-U" seems to be upgrade which would make sense.

My best guess at this point is you are using a system installed python on your Apple and it needs to write to directories that Apple is protection perhaps, again this is just a guess. I don't recommend disabling SID.

If you run "which python" and it shows "/usr/bin/python" that likely confirms you are using a system installed python.

John

**Comment by rahmatawaludin** [comment]
Hi @JohnPolansky thanks for your help. I've use python from homebrew. It successfully install codeintel.. :)

While the project was scanning I got this error:
```
CodeIntel.codeintel.CodeIntelManager: ERROR: Unknown command 'global-prefs-observe', response {'command': 'global-prefs-observe', 'add': ['defaultHTMLDecl'], 'success': True}
CodeIntel.codeintel.CodeIntelManager: ERROR: Error handling unsolicited response
Traceback (most recent call last):
  File "/Users/rahmatawaludin/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel.py", line 833, in handle
    raise ValueError("Unknown unsolicited response \"%s\"" % response_command)
ValueError: Unknown unsolicited response "global-prefs-observe"
```

I'm using codeintel 3 beta 6.

But, the autocomplete and jump are working. Thanks.. :)

**Comment by JohnPolansky** [comment]
I've no idea on the message, that log file does seem to spit out a lot of
debug.. to be honest.. that might be a normal-ish warning.. saying it
couldn't find something that matched but may not be failure. If you are
seeing completion I'd say you are in pretty good shape.

If you do you have problems you might consider deleting your .codeintel..
"rm -rf  ~/.codeintel" when you restart Sublime it will regenerate all
that. Not saying you should do this but if you run into quirkiness you
might try it.

If you don't mind can you share your SublimeCodeIntel.sublime-settings for
your User? I've posted mine here: http://pastebin.com/FPCU6Nv2

I'm just curious what you have in there. it's difficult to follow the
various options you can put in there.

Thanks

**Comment by rahmatawaludin** [comment]
I haven't modified any configuration, so my user config is empty. I'm using default config like this one:
```
/*
    SublimeCodeIntel default settings
*/
{
    /*
        codeintel_live - Enbles/disables live codeintel autocomplete.
    */
    "codeintel_live": true,

    /*
       Maps syntax names to languages. This allows variations on a syntax
       (for example "Python (Django)") to be used. The key is
       the base filename of the .tmLanguage syntax files, and the value
       is the syntax it maps to.
    */
    "codeintel_syntax_map":
    {
       "Python Django": "Python",
       "HTML (Django)": "Django"
    },

    /*
        codeintel_disabled_languages - List of codeintel disabled languages.
    */
    "codeintel_disabled_languages": [],

    /*
        codeintel_oop_command - Executable for OOP codeintel command.
    */
    "codeintel_oop_command": "/usr/local/bin/codeintel",

    /*
        codeintel_log_levels - Set the logging levels for the OOP loggers
        This can be DEBUG, INFO, WARNING or ERROR; WARNGING is recommended,
        other settings might have an impact in the perfocmance.
    */

    "codeintel_log_levels" : ["WARNING"],

    /*
        codeintel_selected_catalogs - API Catalogs.
        SublimeCodeIntel uses API catalogs to provide autocomplete and calltips
        for 3rd-party libraries.

        NOTE: Add only the libraries that you use in your code. Adding all API
            catalogs for a particular language can lead to confusing results.

        Avaliable catalogs:
            PyWin32 (Python3) (for Python3: Python Extensions for Windows)
            PyWin32 (for Python: Python Extensions for Windows)
            Rails (for Ruby: Rails version 1.1.6)
            jQuery (for JavaScript: jQuery JavaScript library - version 1.9.1)
            Prototype (for JavaScript: JavaScript framework for web development)
            dojo (for JavaScript: Dojo Toolkit API - version 1.5.0)
            Ext_30 (for JavaScript: Ext JavaScript framework - version 3.0)
            HTML5 (for JavaScript: HTML5 (Canvas, Web Messaging, Microdata))
            MochiKit (for JavaScript: A lightweight JavaScript library - v1.4.2)
            Mozilla Toolkit (for JavaScript: Mozilla Toolkit API - version 1.8)
            XBL (for JavaScript: XBL JavaScript support - version 1.0)
            YUI (for JavaScript: Yahoo! User Interface Library - v2.8.1)
            Drupal (for PHP: A full-featured PHP content management/discussion engine -- v5.1)
            PECL (for PHP: A collection of PHP Extensions)
    */
    "codeintel_selected_catalogs": ["jQuery", "HTML5"],

    /*
        codeintel_scan_files_in_project - Include all files and directories from
        the project base directory and in the Sublime Text project.
    */
    "codeintel_scan_files_in_project": true,

    /*
        codeintel_max_recursive_dir_depth - Maximum recursion to use, when applicable.
    */
    "codeintel_max_recursive_dir_depth": 10,

    /*
        codeintel_scan_extra_paths - Extra directories to include during the scan,
        additional to the ones configured by default.
    */
    "codeintel_scan_extra_paths": [],

    /*
        codeintel_scan_exclude_paths - Directories to exclude from the scan.
    */
    "codeintel_scan_exclude_paths": ["/build/", "/min/"],

    /*
        codeintel_env - Additional environment variables to use.
    */
    "codeintel_env": {
    },

    /*
        Defines a configuration for each language. Each language can include any
        of the available settings listed above, plus any others passed to CodeIntel.
    */
    "codeintel_language_settings": {
        "Python": {
            "python": ""
        },
        "Python3": {
            "python3": ""
        },
        "Ruby": {
            "ruby": ""
        },
        "Perl": {
            "perl": ""
        },
        "Go": {
            "golangDefaultLocation": "",
            "gocodeDefaultLocation": "",
            "godefDefaultLocation": ""
        },
        "HTML": {
            "defaultHTMLDecl": "-//W3C//DTD HTML 5//EN"
        },
        "HTML5": {
            "defaultHTML5Decl": "-//W3C//DTD HTML 5//EN"
        },
        "JavaScript": {
        },
        "Node.js": {
            "nodejsDefaultInterpreter": ""
        },
        "PHP": {
            "php": "",
            "phpConfigFile": ""
        }
    }
}
```

**Comment by JohnPolansky** [comment]
Gotcha, thanks for the help! Enjoy Hopefully by posting these results
others will find it useful.

**Comment by rahmatawaludin** [comment]
Thanks man.. :)
You might want to contact me if you need PHP + Laravel developer.. lol..
