### ISSUE TITLE
SublimeCodeIntel oop - Windows 10 / ST3 - subprocess import error

### ISSUE THREAD

**Issue by ZiperRom1** [SublimeCodeIntel/SublimeCodeIntel#570]
Hi,

I tried to use the beta version of SublimeCodeIntel oop and I got this error in sublime console

```
Exception in thread CodeIntel Manager Thread:
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Data\Packages\SublimeCodeIntel\libs\process.py", line 91, in <module>
    from subprocess import (SW_HIDE,
ImportError: cannot import name GetVersion

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "C:\Program Files\Sublime Text\Data\Packages\SublimeCodeIntel\libs\codeintel.py", line 764, in run
    self.init_child()
  File "C:\Program Files\Sublime Text\Data\Packages\SublimeCodeIntel\libs\codeintel.py", line 472, in init_child
    import process
  File "C:\Program Files\Sublime Text\Data\Packages\SublimeCodeIntel\libs\process.py", line 96, in <module>
    SW_HIDE = subprocess._subprocess.SW_HIDE
AttributeError: 'module' object has no attribute '_subprocess'
```

It seems subprocess.GetVersion does not exists
It loads the subprocess from the sublime text 3 repository where there is a file python3.3.zip
Do you think I can quickly fix this error by telling your plugin to use a special version of python (compatible with subprocess  GetVersion etc) in putting the right path in any option ?
Thanks

**Comment by Nilpohc** [comment]
HI,
Same here, but I did some research and found a quick fix for this. This is due to the Python version. It requires to modify a bit of code though. Here's how :
- Open the incriminated file ("C:\Program Files\Sublime Text\Data\Packages\SublimeCodeIntel\libs\process.py")
- Go to line 95 which tries to deal with the ImportError exception by importing the subprocess module
- Replace the whole sequence "import subprocess" etc. (lines 95 to 101) with this one :
from _winapi import (SW_HIDE,
                                STARTF_USESTDHANDLES, STARTF_USESHOWWINDOW,
                                GetVersion, CreateProcess, TerminateProcess)
(to make it clean, nothing should be replace and another exception interception should be coded).

Alas, this only removes the exception during the initialisation. Despite that, I was unable to make the CodeIntel work afterwards, but I have no clue why. I tried to force it Ctrl+Alt+Space but no indexing happens and no directory is created. Creating manually the directories doesn't help either.

Wait and see...:-)

**Comment by ZiperRom1** [comment]
Yes I also "hide" the exception raise but the plugin couldn't work.
I am using the classic version of CodeIntel and wait for a real bugfix.
I am not a python developer so I can't really help, sorry.

**Comment by eastdacc** [comment]
Same problem here

**Comment by zixiliuyue** [comment]
This project is dead?

**Comment by adnedelcu** [comment]
From what I can see, the project is not dead, but the main focus is on *unix, not Windows.

My fork has a semi-working version of the oop branch for Windows, but until it's fully working, I suggest going for the 2.0 version.

**Comment by deathaxe** [comment]
Works on Windows 10 x64 with ST3 4142 

1. pull the latest commit from oop branch
2. install https://pypi.python.org/pypi/CodeIntel using pip (I use python 3.6 x64)
3. Open SublimeCodeIntel.sublime-settings
4. Modify `"oop_mode": "tcp",` as Windows's pipes are too stupid.
5. Working...

Someone could hide the console window of codeintel and everything is just fine.

**Comment by adnedelcu** [comment]
@deathaxe, I will try it tomorrow on my Windows machine and come back with a confirmation ;)
