### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by eastdacc** [SublimeCodeIntel/SublimeCodeIntel#573]
Hi 
I am getting this error on windows when codeintel tries to run in a php file in sublime text 3. I have tried running sublime as admin and I get the same error. 
codeintel_word_completions set to all works fine
also if I add PHP to codeintel_selected_catalogs runs fine.
Is autocomplete for project files what seems to fail

	Starting logging SublimeCodeIntel v2.2.0 rev GIT-unknown (1454728598) on Fri Feb  5 22:59:02 2016
=================================================================================================
Updating indexes for 'PHP'... The first time this can take a while.
scan_purelang: path: 'D:\\01_trabajo\\02_clientes\\ces\\web_2015\\frontsite\\web\\index.php' lang: PHP
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 437ms
Doing CodeIntel for 'PHP' (hold on)...
eval 'Ces' at index.php#16  <Trigger 'php-complete-functions' at 424>
function_names_from_scope_starting_with_expr:: expr: 'Ces', scoperef: (<Element 'scope' at 0x0000023C9048BF98>, []) for ('locals', 'namespace', 'globals', 'imports')
function_names_from_scope_starting_with_expr:: adding locals: []
function_names_from_scope_starting_with_expr:: adding globals: []
Unexpected error with evaluator: 'Ces' at index.php#16
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree.py", line 317, in eval
    cplns = self.eval_cplns()
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 230, in eval_cplns
    self._classes_from_scope(self.expr[:3], start_scope) + \
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 531, in _functions_from_scope
    self.function_shortnames_from_elem)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 430, in _element_names_from_scope_starting_with_expr
    for lib in self.libs:
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 187, in libs
    self._libs = self.langintel.libs_from_buf(self.buf)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1008, in libs_from_buf
    libs += self._buf_indep_libs_from_env(env)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1158, in _buf_indep_libs_from_env
    = self._php_info_from_php(php, env)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1061, in _php_info_from_php
    p = process.ProcessOpen(argv, env=env.get_all_envvars())
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\process.py", line 357, in __init__
    creationflags=flags)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
PermissionError: [WinError 5] Access is denied
done eval: eval error
Done 'PHP' CodeIntel! Full CodeIntel took 11ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 4ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 4ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 4ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 4ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 4ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 4ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 0ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 4ms
Doing CodeIntel for 'PHP' (hold on)...
eval 'CesClasses' at index.php#16  <Trigger 'php-complete-static-members' at 436>
_hit_from_citdl:: expr: 'CesClasses', scoperef: (<Element 'scope' at 0x0000023C9048BF28>, [])
_hit_from_citdl:: expr tokens: ['CesClasses']
_hits_from_first_part:: find 'CesClasses ...' starting at (<Element 'scope' at 0x0000023C9048BF28>, []):
_hits_from_first_part:: scoperef now (<Element 'scope' at 0x0000023C9048BF28>, []):
_hits_from_first_part:: checking namespace aliases
_hits_from_first_part:: module: '/../vendor/autoload.php', symbol: None, alias: None
_hits_from_first_part:: module: '/../vendor/yiisoft/yii2/Yii.php', symbol: None, alias: None
_hits_from_first_part:: pt3: is 'CesClasses' accessible on (<Element 'scope' at 0x0000023C9048BF28>, [])? no
Unexpected error with evaluator: 'CesClasses' at index.php#16
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree.py", line 317, in eval
    cplns = self.eval_cplns()
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 310, in eval_cplns
    hit = self._hit_from_citdl(self.expr, start_scope)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 860, in _hit_from_citdl
    hits, nconsumed = self._hits_from_first_part(tokens, scoperef)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 1213, in _hits_from_first_part
    hit, nconsumed = self._hit_from_elem_imports(tokens, elem)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\tree_php.py", line 1230, in _hit_from_elem_imports
    libs = self.buf.libs
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1300, in libs
    return self.langintel.libs_from_buf(self)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1008, in libs_from_buf
    libs += self._buf_indep_libs_from_env(env)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1158, in _buf_indep_libs_from_env
    = self._php_info_from_php(php, env)
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_php.py", line 1061, in _php_info_from_php
    p = process.ProcessOpen(argv, env=env.get_all_envvars())
  File "C:\Users\sanra\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\process.py", line 357, in __init__
    creationflags=flags)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
PermissionError: [WinError 5] Access is denied
done eval: eval error
Done 'PHP' CodeIntel! Full CodeIntel took 16ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 5ms
Doing CodeIntel for 'PHP' (hold on)...
Done 'PHP' CodeIntel! Full CodeIntel took 4ms

**Comment by selamialtin** [comment]
I have seem same problem, 
i change to php_path with full exe name like below         
"php_path": "C:/wamp/bin/php/php5.6.25/php.exe",

and its worked for me.
