### ISSUE TITLE
[PHP] Unexpected error with evaluator

### ISSUE THREAD

**Issue by OnkelTem** [SublimeCodeIntel/SublimeCodeIntel#582]
I've just installed SublimeCodeIntel v. 2.2.0+st3
Sublime version: Build 3103

I opened a PHP file and Super+clicked on an interface name and the CodeIntel began to index. It took some time but finally it finished but nothing happened. I restarted ST several times retried the action but no success.

Then I've discovered codeintel.log, wiped it out and here is the end of one click-session:

```
Unexpected error with evaluator: 'ContentEntityBase' at SyncOp.php#47
Traceback (most recent call last):
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/tree.py", line 331, in eval
    defns = self.eval_defns()
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/tree_php.py", line 370, in eval_defns
    hit = self._hit_from_citdl(self.expr, start_scoperef, defn_only=True)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/tree_php.py", line 860, in _hit_from_citdl
    hits, nconsumed = self._hits_from_first_part(tokens, scoperef)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/tree_php.py", line 1182, in _hits_from_first_part
    hit = self._hit_from_citdl(expr, scoperef)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/tree_php.py", line 860, in _hit_from_citdl
    hits, nconsumed = self._hits_from_first_part(tokens, scoperef)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/tree_php.py", line 1111, in _hits_from_first_part
    hits = self._hits_from_namespace(first_token, scoperef)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/tree_php.py", line 1084, in _hits_from_namespace
    lib_hits = lib.hits_from_lpath(lpath)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/database/multilanglib.py", line 161, in hits_from_lp
ath
    self.ensure_all_dirs_scanned(ctlr=ctlr)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/database/langlibbase.py", line 69, in ensure_all_dir
s_scanned
    dir, ctlr=ctlr, reporter=lambda msg: None)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/database/langlibbase.py", line 104, in ensure_dir_sc
anned
    lang=self.lang)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 462, in buf_from_path
    follow_symlinks=True)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/textinfo.py", line 191, in textinfo_from_path
    quick_determine_lang=quick_determine_lang)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/textinfo.py", line 267, in init_from_path
    self._classify_from_magic(lidb)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/textinfo.py", line 440, in _classify_from_magic
    li = lidb.langinfo_from_magic(head_bytes)
  File "/home/username/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/langinfo.py", line 385, in langinfo_from_magic
    if pattern.search(head_bytes, start):
TypeError: can't use a string pattern on a bytes-like object
done eval: eval error
Done 'PHP' CodeIntel! Full CodeIntel took ~1s
```

**Comment by geeyan** [comment]
+1

**Comment by lanatra** [comment]
+1
