### ISSUE TITLE
Not indexing

### ISSUE THREAD

**Issue by charliekassel** [SublimeCodeIntel/SublimeCodeIntel#601]
I can't seem to get anything indexed.
Im using Sublime build 3114

The log file states:
```
Starting logging SublimeCodeIntel v2.2.0 rev GIT-unknown (1463862087) on Thu May 26 07:04:36 2016
+ Info: processing `PHP': please wait...
```

But doesn't get any further i.e. ~/.codeintel/db dir is empty due to the exception logged in the console below I guess:
```
Exception in thread scanning thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 841, in _codeintel_scan
    buf = mgr.buf_from_content(content, lang, env, path or "<Unsaved>", 'utf-8')
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 440, in buf_from_content
    buf = buf_class(self, accessor, env, path, encoding)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_php.py", line 1289, in __init__
    super(PHPBuffer, self).__init__(*args, **kwargs)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/citadel.py", line 146, in __init__
    Buffer.__init__(self, *args, **kwargs)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/buffer.py", line 123, in __init__
    (s, True) for s in self.comment_styles() + self.string_styles())
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/udl.py", line 472, in comment_styles
    state_map = styles.StateMap["UDL"]
AttributeError: 'module' object has no attribute 'StateMap'
```

I've also installed codeintel using pip

**Comment by rkpatel33** [comment]
Seeing this also now.

**Comment by charliekassel** [comment]
My issue seemed to be resolved with a fresh install on a new computer.
I've not tracked down what the conflict was.

**Comment by ericofranco** [comment]
same issue here.

**Comment by gobijan** [comment]
I have the same issue..

**Comment by gflament** [comment]
Same issue here on a fresh install
`+ Info: processing `PHP': please wait...
Exception in thread scanning thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/home/gflament/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 802, in _codeintel_scan
    mgr = codeintel_manager()
  File "/home/gflament/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 753, in codeintel_manager
    codeintel_database_dir = os.path.expanduser(settings_manager.get("codeintel_database_dir"))
  File "./python3.3/posixpath.py", line 252, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'`
