### ISSUE TITLE
PHP - codeintel2.common.CodeIntelError: style_at_pos

### ISSUE THREAD

**Issue by SAndrle** [SublimeCodeIntel/SublimeCodeIntel#632]
Hallo,

I have a problem with your plugin. I attach a log file. For security reasons I have change file paths.

This error appears in big project - Kohana framework. In small projects is everything OK.

And BTW.: I wasn't able to set .codeintel database location per project.

Thank you

[codeintel.txt](https://github.com/SublimeCodeIntel/SublimeCodeIntel/files/1051758/codeintel.txt)

**Comment by nemesiscb** [comment]
Similar isseus here.
Windows 10, py3. php 5.6
when php files is a bit longer (speaking of at least 5-6 function, about a normal project, a small project), the indexing stops working!
opening a freshly new or an existing files with 1-2-3 functions it works!

```
Starting logging SublimeCodeIntel v2.2.0 rev GIT-unknown (1518514352) on Tue May  8 10:19:43 2018
=================================================================================================
+ Info: processing `PHP': please wait...
Updating indexes for 'PHP'... The first time this can take a while.
scan_purelang: path: 'C:\\xampp\\htdocs\\gest_flussi\\gest_ricezione.php' lang: PHP
+ Info: Updating indexes for 'PHP'... The first time this can take a while.
Doing CodeIntel for 'PHP' (hold on)...
+ Info: Doing CodeIntel for 'PHP' (hold on)...
Exception! C:\xampp\htdocs\gest_flussi\gest_ricezione.php:49343 (PHP)
Traceback (most recent call last):
  File "C:\Users\Salvatore\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 885, in get_trg
    trg = getattr(buf, type, lambda *a: None)(*args)
  File "C:\Users\Salvatore\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\udl.py", line 374, in preceding_trg_from_pos
    lang = self.lang_from_pos(curr_pos-1)
  File "C:\Users\Salvatore\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\udl.py", line 263, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "C:\Users\Salvatore\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\accessor.py", line 223, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "C:\Users\Salvatore\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\accessor.py", line 219, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
codeintel2.common.CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!
+ Info: Error indexing! Please send the log file: 'C:\Users\Salvatore/.codeintel\codeintel.log
Done 'PHP' CodeIntel! Full CodeIntel took ~3s
```
