### ISSUE TITLE
IndexError 

### ISSUE THREAD

**Issue by nooperpudd** [SublimeCodeIntel/SublimeCodeIntel#653]
Sublime Version:  version 3.0 build 3143
SublimeCodeIntel: 2.2.0
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "/Users/jsxf/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1520, in on_selection_modified
    rowcol = view.rowcol(view_sel[0].end())
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
```

**Comment by nocivus** [comment]
+1

**Comment by stychos** [comment]
Same here. Index is not building, logs are empty. Tried both with the stock py2 and the brew's py3.

**Comment by stychos** [comment]
Okay, found out that it's working good with the dev branch of the Sublime Text.

**Comment by ehausen** [comment]
Just noticed this. Any news?
@stychos so running good on ST dev?

Sublime Text 3.1.1 build 3176
CodeIntel v2.2.0
```
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 462, in run_callback
    expr()
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 586, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "/Users/Erik/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1520, in on_selection_modified
    rowcol = view.rowcol(view_sel[0].end())
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
```

**Comment by dnyaneshgate** [comment]
Still getting this issue:
`
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 585, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "/home/dnyaneshg/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1439, in on_modified
    sublime_scope = getSublimeScope(view)
  File "/home/dnyaneshg/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 391, in getSublimeScope
    sel = view_sel[0]
  File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
`

`
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 602, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "/home/dnyaneshg/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1520, in on_selection_modified
    rowcol = view.rowcol(view_sel[0].end())
  File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
`

**Comment by hirschferkel** [comment]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 585, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1439, in on_modified
    sublime_scope = getSublimeScope(view)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 391, in getSublimeScope
    sel = view_sel[0]
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
```

**Comment by hirschferkel** [comment]
After I reinstalled CodeIntel with `pip3 install --upgrade --pre CodeIntel` it's working again!

**Comment by charly22** [comment]
+1

**Comment by lonsty** [comment]
+1
