### ISSUE TITLE
Can't install CodeIntel

### ISSUE THREAD

**Issue by smoggach** [SublimeCodeIntel/SublimeCodeIntel#669]
I am on OSX 10.13.4 with python 2.7
Your instructions indicate that we must install CodeIntel using pip. When I try to do so this is the output I receive:

`pip install -U CodeIntel
Collecting CodeIntel
  Downloading https://files.pythonhosted.org/packages/b9/e1/e8de333336f3b9ff2d3efa3be1468d633f7a504ff4787c2159470ab7157c/CodeIntel-2.0.0-cp27-cp27m-macosx_10_12_x86_64.whl (21.1MB)
    100% |████████████████████████████████| 21.1MB 507kB/s 
Collecting clang (from CodeIntel)
  Downloading https://files.pythonhosted.org/packages/b2/2a/5ab52ae9d9e7684b66062e953a0cbdf326a35657aaf59cd31a09b7b86504/clang-6.0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l5/l0yvnnqd44z2066t6nfp_0cc0000gn/T/pip-install-CKOqZV/clang/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function`

:(

**Comment by J0hannB** [comment]
Yep, same issue here as well

**Comment by ftwater** [comment]
yeah,me too,i don't know if it successed

**Comment by CodeBrauer** [comment]
`~/.codeintel/` was created, so maybe it was installed?

However here is my errorlog:
```
(10:02:03) ~ ➜ pip3 install -U CodeIntel
Collecting CodeIntel
  Using cached https://files.pythonhosted.org/packages/0a/24/141db0d6c64453e6848849979b9c527d3547ad1552674763000e9da2a648/CodeIntel-2.0.0.tar.gz
Collecting 3to2 (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/8f/ab/58a363eca982c40e9ee5a7ca439e8ffc5243dde2ae660ba1ffdd4868026b/3to2-1.1.1.zip
Collecting applib (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/d4/20/67c3c98b557cfa2aa95dc0a9281989e6ab740a5058ee1f8a5f8febba8aaf/applib-1.2.tar.gz
Collecting chardet (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cmdln (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/26/23/7654219ac89aa48190341b7c7114fea21e21889693def5f625ef2a218d5d/cmdln-2.0.0.zip
Collecting esprima (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/86/61/ff7a62bcf79cebb6faf42c0ff28756c152a9dcf7244019093ca4513d80ee/esprima-4.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f2/27mglkvn37g72_v3ggmgzv_800010b/T/pip-install-hb9gg_rl/esprima/setup.py", line 8, in <module>
        from esprima import version
      File "/private/var/folders/f2/27mglkvn37g72_v3ggmgzv_800010b/T/pip-install-hb9gg_rl/esprima/esprima/__init__.py", line 29, in <module>
        from .esprima import *  # NOQA
      File "/private/var/folders/f2/27mglkvn37g72_v3ggmgzv_800010b/T/pip-install-hb9gg_rl/esprima/esprima/esprima.py", line 26, in <module>
        from .comment_handler import CommentHandler
      File "/private/var/folders/f2/27mglkvn37g72_v3ggmgzv_800010b/T/pip-install-hb9gg_rl/esprima/esprima/comment_handler.py", line 27, in <module>
        from .nodes import Node
      File "/private/var/folders/f2/27mglkvn37g72_v3ggmgzv_800010b/T/pip-install-hb9gg_rl/esprima/esprima/nodes.py", line 61
        self.async = False
                 ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/f2/27mglkvn37g72_v3ggmgzv_800010b/T/pip-install-hb9gg_rl/esprima/
(10:02:13) ~ ➜ pip2.7 install -U CodeIntel
Collecting CodeIntel
  Using cached https://files.pythonhosted.org/packages/a3/d5/5fde2d4b613bad98b00e319e4cfd532c41e1dc637665e813f1b5671622df/CodeIntel-2.0.0-cp27-cp27m-macosx_10_11_x86_64.whl
Requirement not upgraded as not directly required: chardet in /usr/local/lib/python2.7/site-packages (from CodeIntel) (3.0.4)
Collecting esprima (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/86/61/ff7a62bcf79cebb6faf42c0ff28756c152a9dcf7244019093ca4513d80ee/esprima-4.0.0.tar.gz
Collecting zope.cachedescriptors (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/81/6f/d668102e1bd4fba6cfb160e178477b4e5ade20ccac0b2b390d4f64d0bb9d/zope.cachedescriptors-4.3.1-py2.py3-none-any.whl
Collecting inflector (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/c4/51/d3cc209c8a0471ef5a04ac750f203b5b486fc70e6cb51c96d99decd49bc4/Inflector-2.0.12.tar.gz
Collecting 3to2 (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/8f/ab/58a363eca982c40e9ee5a7ca439e8ffc5243dde2ae660ba1ffdd4868026b/3to2-1.1.1.zip
Collecting applib (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/d4/20/67c3c98b557cfa2aa95dc0a9281989e6ab740a5058ee1f8a5f8febba8aaf/applib-1.2.tar.gz
Requirement not upgraded as not directly required: six in /usr/local/lib/python2.7/site-packages (from CodeIntel) (1.10.0)
Collecting cmdln (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/26/23/7654219ac89aa48190341b7c7114fea21e21889693def5f625ef2a218d5d/cmdln-2.0.0.zip
Collecting clang (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/b2/2a/5ab52ae9d9e7684b66062e953a0cbdf326a35657aaf59cd31a09b7b86504/clang-6.0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f2/27mglkvn37g72_v3ggmgzv_800010b/T/pip-install-6S0oDu/clang/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/f2/27mglkvn37g72_v3ggmgzv_800010b/T/pip-install-6S0oDu/clang/
```

**Comment by bauerpm7** [comment]
similar problem as CodeBrauer
`$ sudo -H pip3 install -U CodeIntel
Collecting CodeIntel
  Using cached https://files.pythonhosted.org/packages/0a/24/141db0d6c64453e6848849979b9c527d3547ad1552674763000e9da2a648/CodeIntel-2.0.0.tar.gz
Collecting 3to2 (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/8f/ab/58a363eca982c40e9ee5a7ca439e8ffc5243dde2ae660ba1ffdd4868026b/3to2-1.1.1.zip
Collecting applib (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/d4/20/67c3c98b557cfa2aa95dc0a9281989e6ab740a5058ee1f8a5f8febba8aaf/applib-1.2.tar.gz
Collecting chardet (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cmdln (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/26/23/7654219ac89aa48190341b7c7114fea21e21889693def5f625ef2a218d5d/cmdln-2.0.0.zip
Collecting esprima (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/86/61/ff7a62bcf79cebb6faf42c0ff28756c152a9dcf7244019093ca4513d80ee/esprima-4.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-nxrkmqa0/esprima/setup.py", line 8, in <module>
        from esprima import version
      File "/private/tmp/pip-install-nxrkmqa0/esprima/esprima/__init__.py", line 29, in <module>
        from .esprima import *  # NOQA
      File "/private/tmp/pip-install-nxrkmqa0/esprima/esprima/esprima.py", line 26, in <module>
        from .comment_handler import CommentHandler
      File "/private/tmp/pip-install-nxrkmqa0/esprima/esprima/comment_handler.py", line 27, in <module>
        from .nodes import Node
      File "/private/tmp/pip-install-nxrkmqa0/esprima/esprima/nodes.py", line 61
        self.async = False
                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-nxrkmqa0/esprima/`

**Comment by CristianIahn** [comment]
Same probleam as @bauerpm7  but on w10x64.

Running CMD as admin., trind pip and pip3, same output.
`C:\Users\crist>pip3 install --upgrade CodeIntel
Collecting CodeIntel
  Using cached https://files.pythonhosted.org/packages/0a/24/141db0d6c64453e6848849979b9c527d3547ad1552674763000e9da2a648/CodeIntel-2.0.0.tar.gz
Collecting 3to2 (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/8f/ab/58a363eca982c40e9ee5a7ca439e8ffc5243dde2ae660ba1ffdd4868026b/3to2-1.1.1.zip
Collecting applib (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/d4/20/67c3c98b557cfa2aa95dc0a9281989e6ab740a5058ee1f8a5f8febba8aaf/applib-1.2.tar.gz
Collecting chardet (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cmdln (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/26/23/7654219ac89aa48190341b7c7114fea21e21889693def5f625ef2a218d5d/cmdln-2.0.0.zip
Collecting esprima (from CodeIntel)
  Using cached https://files.pythonhosted.org/packages/86/61/ff7a62bcf79cebb6faf42c0ff28756c152a9dcf7244019093ca4513d80ee/esprima-4.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\crist\AppData\Local\Temp\pip-install-teq9liwt\esprima\setup.py", line 8, in <module>
        from esprima import version
      File "C:\Users\crist\AppData\Local\Temp\pip-install-teq9liwt\esprima\esprima\__init__.py", line 29, in <module>
        from .esprima import *  # NOQA
      File "C:\Users\crist\AppData\Local\Temp\pip-install-teq9liwt\esprima\esprima\esprima.py", line 26, in <module>
        from .comment_handler import CommentHandler
      File "C:\Users\crist\AppData\Local\Temp\pip-install-teq9liwt\esprima\esprima\comment_handler.py", line 27, in <module>
        from .nodes import Node
      File "C:\Users\crist\AppData\Local\Temp\pip-install-teq9liwt\esprima\esprima\nodes.py", line 61
        self.async = False
                 ^
    SyntaxError: invalid syntax`

**Comment by Kronuz** [comment]
This is being addressed in https://github.com/Kronuz/esprima-python/pull/8 when ready, I’ll make a new CodeIntel release.

**Comment by externl** [comment]
Any workarounds in the meantime, https://github.com/Kronuz/esprima-python/pull/8 doesn't seem to be moving anywhere.
