### ISSUE TITLE
Silvercity import issue on Ubunut 18.04 with Sublime text 3 build 3180

### ISSUE THREAD

**Issue by saurabh-gohil** [SublimeCodeIntel/SublimeCodeIntel#682]
Getting Silvercity import error as below
`Traceback (most recent call last):
  File "/home/saurabhg/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/_SilverCity.py", line 12, in <module>
    from _local_arch._SilverCity import *
ImportError: No module named '_local_arch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/saurabhg/.config/sublime-text-3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 109, in <module>
    from codeintel2.common import CodeIntelError, EvalTimeout, LogEvalController, TRG_FORM_CPLN, TRG_FORM_CALLTIP, TRG_FORM_DEFN
  File "/home/saurabhg/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/codeintel2/common.py", line 86, in <module>
    import SilverCity
  File "/home/saurabhg/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/SilverCity/__init__.py", line 1, in <module>
    import _SilverCity
  File "/home/saurabhg/.config/sublime-text-3/Packages/SublimeCodeIntel/libs/_SilverCity.py", line 20, in <module>
    from _linux_libcpp6_x86_64_py33._SilverCity import *
ImportError: /home/saurabhg/.config/sublime-text-3/Packages/SublimeCodeIntel/arch/_linux_libcpp6_x86_64_py33/_SilverCity.so: undefined symbol: PyExc_ValueError`

Kindly help to resolve the issue.

**Comment by kaliomar** [comment]
Don't install Sublimecodeintel from the package control, clone the developer version and put it in this path /home/saurabhg/.config/sublime-text-3/Packages/

hope it works with you

**Comment by saurabh-gohil** [comment]
> Don't install Sublimecodeintel from the package control, clone the developer version and put it in this path /home/saurabhg/.config/sublime-text-3/Packages/
> 
> hope it works with you

Thanks for the help. I cloned the repo as mentioned and error is gone now. However, Go to definition is not working and I am getting below message in sublime console.

`Consider setting library_path`

Any Idea?
