### ISSUE TITLE
Updating indexes

### ISSUE THREAD

**Issue by Jose-Alberto** [SublimeCodeIntel/SublimeCodeIntel#707]
Starting logging SublimeCodeIntel v2.2.0 rev GIT-unknown (1592254704) on Sat Jun 20 14:50:33 2020
=================================================================================================
Updating indexes for 'JavaScript'... The first time this can take a while.
addClassOrVariableMember: funciones.js:1937 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:1938 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:2095 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:2096 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3048 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3049 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3302 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3303 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3362 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3363 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3765 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3766 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3960 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3961 Trying to add ['timer'] as a local member variable??
+ Info: Updating indexes for 'JavaScript'... The first time this can take a while.
Doing CodeIntel for 'JavaScript' (hold on)...
Exception! C:\xampp\htdocs\sicepol\views\assets\js\funciones.js:55942 (JavaScript)
Traceback (most recent call last):
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 885, in get_trg
    trg = getattr(buf, type, lambda *a: None)(*args)
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\buffer.py", line 175, in trg_from_pos
    return self.langintel.trg_from_pos(self, pos, implicit)
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_javascript.py", line 402, in trg_from_pos
    if accessor.style_at_pos(p) != last_style:
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\accessor.py", line 223, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\accessor.py", line 219, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
codeintel2.common.CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!
Done 'JavaScript' CodeIntel! Full CodeIntel took ~2s
Doing CodeIntel for 'JavaScript' (hold on)...
Done 'JavaScript' CodeIntel! Full CodeIntel took 318ms
Updating indexes for 'JavaScript'... The first time this can take a while.
addClassOrVariableMember: funciones.js:1937 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:1938 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:2095 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:2096 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3048 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3049 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3302 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3303 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3362 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3363 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3765 Trying to add ['showConfirmButton'] as a local member variable??
+ Info: Updating indexes... The first time this can take a while. Do not despair!
addClassOrVariableMember: funciones.js:3766 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3960 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3961 Trying to add ['timer'] as a local member variable??
Doing CodeIntel for 'JavaScript' (hold on)...
Exception! C:\xampp\htdocs\sicepol\views\assets\js\funciones.js:55944 (JavaScript)
Traceback (most recent call last):
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 885, in get_trg
    trg = getattr(buf, type, lambda *a: None)(*args)
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\buffer.py", line 175, in trg_from_pos
    return self.langintel.trg_from_pos(self, pos, implicit)
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\lang_javascript.py", line 414, in trg_from_pos
    style = accessor.style_at_pos(p)
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\accessor.py", line 223, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "C:\Users\José Alberto\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel2\accessor.py", line 219, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
codeintel2.common.CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!
+ Info: Error indexing! Please send the log file: 'C:\Users\José Alberto/.codeintel\codeintel.log
Done 'JavaScript' CodeIntel! Full CodeIntel took ~3s
Updating indexes for 'JavaScript'... The first time this can take a while.
addClassOrVariableMember: funciones.js:1937 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:1938 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:2095 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:2096 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3048 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3049 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3302 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3303 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3362 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3363 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3765 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3766 Trying to add ['timer'] as a local member variable??
addClassOrVariableMember: funciones.js:3960 Trying to add ['showConfirmButton'] as a local member variable??
addClassOrVariableMember: funciones.js:3961 Trying to add ['timer'] as a local member variable??
+ Info: Updating indexes for 'JavaScript'... The first time this can take a while.

**Comment by Jose-Alberto** [comment]
Solucioné el problema instalando el programa ImageMagick-7.0.10-20-Q16-HDRI-x64-dll.exe, luego de 3 reinicios del programa logró funcionar

**Comment by Jose-Alberto** [comment]
Solucioné el problema instalando el programa ImageMagick-7.0.10-20-Q16-HDRI-x64-dll.exe, luego de 3 reinicios del programa logró funcionar
