### ISSUE TITLE
CodeIntel broken on fresh install (maybe related to macOS Big Sur)

### ISSUE THREAD

**Issue by zachriggle** [SublimeCodeIntel/SublimeCodeIntel#709]
After installation in Package Control and trying to `Ctrl-Click` on a variable name to jump to its definition, but I nothing happens and an exception is thrown which can be seen in the console.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/Users/zachriggle/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1613, in run
    lang = guess_lang(view, path)
  File "/Users/zachriggle/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 459, in guess_lang
    mgr = None if settings_manager._settings_id is None else codeintel_manager()
  File "/Users/zachriggle/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 753, in codeintel_manager
    codeintel_database_dir = os.path.expanduser(settings_manager.get("codeintel_database_dir"))
  File "./python3.3/posixpath.py", line 252, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'
```

If it helps any, this happens on macOS Big Sur, with the latest CodeIntel installed via Package Control.  (Package Control itself is broken on Big Sur, but there's a workaround here: https://forum.sublimetext.com/t/package-control-testing/53923)

**Comment by srbetasign** [comment]
Hello,

I have faced the same issue.

I have not found a solution to remove SublimeCodeIntel.

see. https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/711#issuecomment-2490924176

EDIT:

I have found a way to fix Sublime Text : https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/711#issuecomment-2491067953
