### ISSUE TITLE
Not working on Apple M1 Max

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [SublimeCodeIntel/SublimeCodeIntel#715]
```
reloading python 3.3 plugin SublimeCodeIntel.ordereddict
reloading python 3.3 plugin SublimeCodeIntel.SublimeCodeIntel
Traceback (most recent call last):
  File "/Users/myuser/config/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/_SilverCity.py", line 12, in <module>
    from _local_arch._SilverCity import *
ImportError: No module named '_local_arch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/myuser/config/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 109, in <module>
    from codeintel2.common import CodeIntelError, EvalTimeout, LogEvalController, TRG_FORM_CPLN, TRG_FORM_CALLTIP, TRG_FORM_DEFN
  File "/Users/myuser/config/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/common.py", line 86, in <module>
    import SilverCity
  File "/Users/myuser/config/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/SilverCity/__init__.py", line 1, in <module>
    import _SilverCity
  File "/Users/myuser/config/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/_SilverCity.py", line 16, in <module>
    from _macosx_universal_py33._SilverCity import *
ImportError: dlopen(/Users/myuser/config/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/arch/_macosx_universal_py33/_SilverCity.so, 0x0002): tried: '/Users/myuser/config/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/arch/_macosx_universal_py33/_SilverCity.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/_SilverCity.so' (no such file)
```

**Comment by mxdbeen** [comment]
How did you fix ur problem?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Not using this anymore :)

**Comment by mxdbeen** [comment]
any alternative plugins can use?

**Comment by mxdbeen** [comment]
ok, i use Anaconda now
